export const brockhausEmbedJson = {
  detailsSnippet:
    "    <style>\n    \n.edusharing_rendering_metadata_body .mdsGroup{\n    flex: 1;\n    padding: 0 20px;\n    min-width: 25%;\n}\n.edusharing_rendering_metadata_body .mdsCaption{\n    border-bottom: 1px solid #6f6f6f;\n    color: #6f6f6f;\n    padding: 8px 15px;\n    font-size: 130%;\n    height: auto;\n    margin: 30px 0 0;\n    font-weight: normal;\n}\n.edusharing_rendering_metadata_body .mdsWidgetCaption{\n    display: block;\n    font-style: italic;\n    font-size: unset;\n    color: #6f6f6f;\n    margin: 15px 0 0 15px;\n    line-height: 1.5;\n}\n\n.edusharing_rendering_metadata_body .mdsWidget:not(.mdsWidget_tinyMCE)  .mdsWidgetContent{\n    white-space: pre-line;\n}\n.edusharing_rendering_metadata_body .mdsWidget_tinyMCE  .mdsValue > div > p:first-child {\n    margin-top: 0;\n}\n\n.edusharing_rendering_metadata_body .mdsWidgetContent .mdsValue{\n    display: inline-flex;\n    margin: 3px 0 0 15px;\n    line-height: 1.5;\n}\n.edusharing_rendering_metadata_body .mdsWidgetMultivalue{\n    margin: 5px 0 0 8px;\n}\n.edusharing_rendering_metadata_body .mdsWidgetMultivalue .mdsValue{\n    display: inline-block;\n    color: #383838;\n    background-color: #F4F4F4;\n    border-radius: 16px;\n    padding: 5px 10px;\n    margin-left: 10px;\n}\n\n.edusharing_rendering_metadata_body .mdsWidget_vcard .mdsValue {\n    display: inline-flex;\n    font-style: italic;\n}\n\n.edusharing_rendering_metadata_body .mdsWidgetContent .mdsValue > i {\n    font-size: 18px;\n    margin-right: 5px;\n    vertical-align: middle;\n}\n\n.edusharing_rendering_metadata_body .mdsWidgetContent .mdsValue > * {\n    margin: auto;\n}\n\n.edusharing_rendering_metadata_body .mdsContributorTitle {\n    font-weight: 600;\n    font-style: normal;\n    margin: 25px 0 -10px 0;\n    color: #000;\n}\n\n.edusharing_rendering_metadata_body .mdsContributorGroup .mdsWidgetCaption,\n.edusharing_rendering_metadata_body .mdsContributorGroup .mdsValue{\n    margin-left: 0;\n    margin-right: 10px;\n}\n\n/* Produce a proper bounding box for focus styles (not provided here). */\n.edusharing_rendering_metadata_body .mds_license a {\n    display: inline-flex;\n    flex-direction: column;\n    gap: 6px;\n}\n.edusharing_rendering_metadata_body .mds_license img {\n    height: 30px;\n    width: auto;\n}\n.edusharing_rendering_metadata_body .mds_license .licenseName {\n    font-weight: bold;\n}\n.edusharing_rendering_metadata_body .mds_license .licenseDescription {\n    color: #6f6f6f;\n    font-size: 90%;\n}\n\n.edusharing_rendering_metadata_body .mds_material_feedback{\n    background: #4D799A;\n    width: 60%;\n    max-width: 220px;\n    margin: 16px auto 8px;\n    border-radius: 3px;\n    box-shadow: 2px 2px 4px 0px rgba(0,0,0,0.25);\n    transition: 0.5s ease-in-out;\n}\n\n.edusharing_rendering_metadata_body .mds_material_feedback .mdsValue{\n    width: 100%;\n    margin: 4px auto;\n}\n\n.edusharing_rendering_metadata_body .mds_material_feedback a{\n    color: #fff;\n    font-weight: 500;\n    display: flex;\n    justify-content: center;\n    padding: 4px 0;\n}\n.edusharing_rendering_metadata_body .mds_material_feedback a:hover,\n.edusharing_rendering_metadata_body .mds_material_feedback a:visited{\n    color: #fff;\n    text-decoration: none;\n}\n\n.edusharing_rendering_metadata_body .mds_material_feedback a i{\n    padding-right: 8px;\n}\n\n\n@media (max-width: 1400px) {\n    .edusharing_rendering_metadata_body .mdsGroup{\n        min-width:50%;\n    }\n}\n\n@media (max-width: 700px) {\n    .edusharing_rendering_metadata_body {\n        display: block;\n    }\n\n    .edusharing_rendering_metadata_body .mdsGroup {\n        display: block;\n        padding: 0;\n    }\n}\n    \n@font-face {\nfont-family: 'Material Icons';\nfont-style: normal;\nfont-weight: 400;\nsrc: url('https://rendering.services.staging.cloud.schulcampus-rlp.de:443/esrender/vendor/fonts/materialicons/MaterialIcons-Regular.eot'); /* For IE6-8 */\nsrc: local('Material Icons'),\nlocal('MaterialIcons-Regular'),\nurl('https://rendering.services.staging.cloud.schulcampus-rlp.de:443/esrender/vendor/fonts/materialicons/MaterialIcons-Regular.woff2') format('woff2'),\nurl('https://rendering.services.staging.cloud.schulcampus-rlp.de:443/esrender/vendor/fonts/materialicons/MaterialIcons-Regular.woff') format('woff'),\nurl('https://rendering.services.staging.cloud.schulcampus-rlp.de:443/esrender/vendor/fonts/materialicons/MaterialIcons-Regular.ttf') format('truetype');\n}\n\n.edusharing_rendering_content_wrapper {\nmin-width: 300px;\nline-height: 1.2;\n}\n.edusharing_rendering_content_video_options_container_expanded {\nbackground: rgba(0, 0, 0, 0.6);\n}\ndiv.edusharing_rendering_content_video_options {\nposition: absolute;\ntop: 2%;\nright: 2%;\ncolor: #fff;\nmargin: 0;\npadding: 5px;\ntext-align: right;\n}\n.edusharing_rendering_content_video_options_container {\ndisplay: flex;\nflex-direction: column;\nalign-items: flex-end;\nposition: absolute;\ntop: 2%;\nright: 2%;\ncolor: #fff;\nmargin: 0;\ntext-align: right;\n}\n.edusharing_rendering_content_video_options {\ndisplay: flex;\nbackground: none;\nborder: none;\ncolor: #fff;\npadding: 5px;\ncursor: pointer;\n}\n\ndiv.edusharing_rendering_content_video_options i {\nopacity: 0.8;\ncursor: pointer;\n}\n\ndiv.edusharing_rendering_content_video_options_content {\ndisplay: none;\n}\n\n.edusharing_rendering_content_video_options_container_expanded .edusharing_rendering_content_video_options_content {\ndisplay: block;\n}\n\ndiv.edusharing_rendering_content_video_wrapper {\ndisplay: inline-block;\nposition: relative;\n}\n\ndiv.edusharing_rendering_content_video_wrapper:hover div.edusharing_rendering_content_video_options {\ndisplay: block;\n}\n\nul.edusharing_rendering_content_video_options_resolutions {\npadding: 0;\nmargin: 0;\nfont-size: 18px !important;\n}\n\nul.edusharing_rendering_content_video_options_resolutions i {\nvertical-align: middle;\nmargin-right: 10px;\nfont-size: 18px !important;\n}\n\ni.edusharing_rendering_content_video_options_toggle {\ntext-shadow: 0px 0px 4px #333;\n}\n\nul.edusharing_rendering_content_video_options_resolutions > li {\ncursor: pointer;\npadding: 4px 0;\nlist-style: none;\n}\n\nul.edusharing_rendering_content_video_options_resolutions > li.edusharing_rendering_content_video_options_resolutions_converting {\ncolor: #999999\n}\n\n.material-icons {\nfont-family: 'Material Icons';\nfont-weight: normal;\nfont-style: normal;\nfont-size: 24px;  /* Preferred icon size */\ndisplay: inline-block;\nline-height: 1;\ntext-transform: none;\nletter-spacing: normal;\nword-wrap: normal;\nwhite-space: nowrap;\ndirection: ltr;\n\n/* Support for all WebKit browsers. */\n-webkit-font-smoothing: antialiased;\n/* Support for Safari and Chrome. */\ntext-rendering: optimizeLegibility;\n\n/* Support for Firefox. */\n-moz-osx-font-smoothing: grayscale;\n\n/* Support for IE. */\nfont-feature-settings: 'liga';\n}\n\n.edusharing_metadata_wrapper {\nmargin-left: 10px;\n}\n\n.edusharing_metadata_toggle_button {\nwidth: 30px; height: 30px; display: inline-block;\nborder-left: 1px solid #cdcdcd;\npadding-left: 5px;\ncursor:pointer;\npadding-top: 3px;\ncolor: #4D799A;\ntransition: ease-in-out 0.3s;\n}\n\n.edusharing_metadata_toggle_button:hover {\ncolor: #00a0d2;\n}\n\n.edusharing_metadata {\nposition: absolute;\nmargin-top: 4px;\nmargin-left: -295px;\nwidth: 350px;\npadding: 11px 0px;\nz-index: 50;\n}\n\n.edusharing_metadata_inner {\ndisplay: flex;\nflex-direction: column;\nalign-items: center;\njustify-content: space-between;\nbackground-color: #f6f6f6;\nborder: 1px solid #ddd;\nborder-radius: 6px;\nbox-shadow: 2px 2px 6px rgba(0, 0, 0, .2);\nmax-height:500px;\noverflow-y: auto;\nfont-size: .9em;\nline-height: 1;\ntransition: ease-in-out 0.3s;\n}\n\n.edusharing_metadata_inner img {\nheight: 16px;\n}\n\n.edusharing_metadata_inner .mdsGroup .mdsCaption {\nfont-size: 1.5em;\nheight: auto;\npadding-bottom: 10px;\nmargin: 0;\n}\n\n.edusharing_rendering_metadata_body .mdsCaption{\nborder-bottom: 1px solid #777 !important;\ncolor: #777 !important;\npadding: 0 12px !important;\nmargin-top: 0 !important;\n}\n\n.edusharing_metadata:before {\nborder-bottom: 15px solid #ddd;\nborder-left: 15px solid transparent;\nborder-right: 15px solid transparent;\ntop: -4px;\ncontent: \"\";\nposition: absolute;\nright: 23px;\nwidth: 0;\nheight: 0;\n}\n\n.edusharing_metadata:after {\nborder-bottom: 15px solid #f6f6f6;\nborder-left: 15px solid transparent;\nborder-right: 15px solid transparent;\ntop: -3px;\ncontent: \"\";\nposition: absolute;\nright: 23px;\nwidth: 0;\nheight: 0;\n}\n\n.mdsGroup {\nbackground: #fff;\nmargin: 8px;\npadding: 12px 0;\nborder: 1px solid #ddd;\n}\n\n.mdsGroup .mdsWidget {\ndisplay: flex;\nflex-wrap: wrap;\nalign-items: baseline;\n}\n\n.mdsGroup .mdsWidget .mdsWidgetCaption {\ncolor: #aaa;\nfont-weight: 500;\n}\n\n.edusharing_rendering_metadata_body .mdsGroup{\nwidth: 94%;\npadding: 12px 0;\nborder-radius: 4px;\n}\n\n.edusharing_rendering_metadata_body .licenseName {\nmargin-top: 8px;\n}\n\n.edusharing_rendering_metadata_body .mdsContributorTitle {\nmargin: 0 !important;\nmargin-top: 25px !important;\n}\n\n.mdsGroup:first-child {\n\n}\n\n.edusharing_metadata_inner .mdsGroup .mdsContributorGroup {\nmargin-left: 15px;\n}\n\n.edusharing_warning {\ndisplay: inline-block;\nbackground-color: #c6c6c6;\ncolor: #383838;\npadding: 5px;\nborder-radius: 3px;\n}\n\n.edusharing_rendering_content_footer {\nwidth: 100%;\nbackground: #f6f6f6;\npadding: 6px;\n}\n\n.edusharing_rendering_content_footer a, .edusharing_rendering_content_footer a:visited, .edusharing_rendering_content_footer a:focus, .edusharing_rendering_content_footer a:hover {\ncolor: #4D799A;\n}\n\n.edusharing_rendering_content_footer_top {\noverflow-y: hidden;\noverflow-x: hidden;\ndisplay: flex;\nalign-items: center;\njustify-content: space-between;\nmin-height: 2rem;\n}\n\n.edusharing_rendering_content_footer_bot {\n}\n\n.edusharing_rendering_content_footer_metadata {\nwidth: 30px;\npadding: 10px;\n}\n\n.edusharing_rendering_content_footer_sequence {\nposition: relative;\n\n}\n\n.edusharing_rendering_content_footer_directory {\nwidth: 100%;\nbackground: #f6f6f6;\npadding: 12px;\n}\n\n.edusharing_rendering_content_footer_directory_img{\nmax-height: 33px;\n}\n\n.edusharing_rendering_content_footer_directory_header {\ndisplay: flex;\nalign-items: center;\njustify-content: space-between;\n}\n\n.edusharing_rendering_content_footer_directory_header a {\ncolor: #4D799A;\n}\n\n.edusharing_rendering_content_footer_directory_header a:hover {\ntext-decoration: none;\n}\n\n.edusharing_rendering_content_footer_directory_toggle > * {\nmargin-right: 20px;\n}\n\n.edusharing_rendering_content_footer_directory_creator {\ndisplay:block;\ncolor: #999;\nfont-size: 90%;\n}\n\n.edusharing_rendering_content_footer_sequence .material-icons {\nvertical-align: middle !important;\n}\n\n.edusharing_rendering_content_footer_directory .material-icons {\nvertical-align: middle !important;\n}\n\n.edusharing_rendering_content_footer_sequence_toggle, .edusharing_rendering_content_footer_directory_toggle {\ncolor: #4D799A;\ncursor:pointer;\ndisplay: flex;\nalign-items: center;\n}\n\n.edusharing_rendering_content_footer_sequence_toggle {\nmargin-top: 6px;\n}\n\n.edusharing_rendering_content_footer_directory_toggle {\ndisplay: flex;\nalign-items: center;\nwidth: 100%;\n}\n\n.edusharing_rendering_content_footer_sequence ul {\npadding: 12px;\nposition: absolute;\nz-index: 49;\nbackground: #f6f6f6;\nwidth: calc(100% + 12px);\nmargin-left: -6px;\n}\n\n.edusharing_rendering_content_footer_directory ul {\nmargin: 10px 0 0 0;\nbackground: #f6f6f6;\nwidth: 100%;\npadding: 0 !important;\n}\n\n.edusharing_rendering_content_footer_sequence ul li, .edusharing_rendering_content_footer_directory ul li {\nlist-style: none;\nheight: 60px;\nbackground: #fff;\nfont-size: 14px;\nmargin: 3px 0;\ndisplay: flex;\nalign-items: center;\nwidth: 100%;\nborder-radius: 3px;\n}\n\n.edusharing_rendering_content_footer_sequence ul li a, .edusharing_rendering_content_footer_directory ul li a {\ndisplay: flex;\nalign-items: center;\ncolor: #383838;\ntext-decoration: none;\nwidth: 100%;\n}\n\n.edusharing_rendering_content_footer_sequence ul li a:hover, .edusharing_rendering_content_footer_directory ul li a:hover {\ncolor: #383838;\ntext-decoration: none;\n}\n\n.edusharing_rendering_content_footer_sequence ul li img, .edusharing_rendering_content_footer_directory ul li img {\nmargin: 10px;\n}\n\n.edusharing_rendering_content_footer_sequence_showall {\nmargin-bottom: 0;\ntext-align: right;\ndisplay: inline-block;\nwidth: 100%;\nmargin-top: 8px;\n}\n\n.edusharing_rendering_content_footer_top .license {\ndisplay: flex;\nflex-wrap:wrap;\nalign-items: center;\n}\n\n.edusharing_rendering_content_footer_top .license .license_link {\ndisplay: inline-flex;\n}\n\nvideo, audio {\nmargin-bottom: -6px;\nborder: 0;\n}\n\n.edu_audio_wrapper{\ndisplay: inline-block;\nmin-width: 70%;\n}\n\n.dataProtectionRegulations {\nposition: relative;\naspect-ratio: 16 / 9;\nmax-width: 800px;\n}\n.dataProtectionRegulations, .dataProtectionRegulationsDialog {\nbackground: #fff;\npadding: 20px;\n-webkit-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.3);\n-moz-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.3);\nbox-shadow: 0px 2px 3px 0px rgba(0,0,0,0.3);\ntext-align: center;\nbackground: #f6f6f6;\nmargin: auto;\nborder: 0;\n}\n.dataProtectionRegulations .dataProtectionRegulationsContainer {\nposition: absolute;\nwidth: 100%;\nz-index: 1;\ncolor: #fff !important;\ntext-shadow: 0 0 5px rgba(0,0,0,.5);\npadding: 15px 20px;\nbackdrop-filter: blur(4px);\nbackground-color: rgba(0,0,0,.6);\nleft: 0;\nbottom: 0;\n}\n.dataProtectionRegulations .dataProtectionRegulationsContainer p{\ncolor: #fff !important;\n}\n.dataProtectionRegulations .dataProtectionRegulationsContainer a:not(.btn) {\ncolor: #B6D8FC;\ntext-decoration: underline;\n}\n.dataProtectionRegulations .dataProtectionVideoBg {\nposition: absolute;\nleft: 0;\ntop: 0;\nobject-fit: cover;\nwidth: 100%;\nheight: 100%;\n}\n\n.dataProtectionRegulationsHeading {\nfont-size: 1.6em;\n}\n\na.edusharing_rendering_content {\nmargin-top: 20px;\nmargin-left: 10px;\nmargin-right: 10px;\n}\n\n.cdk-visually-hidden {\nborder: 0;\nclip: rect(0 0 0 0);\nheight: 1px;\nmargin: -1px;\noverflow: hidden;\npadding: 0;\nposition: absolute;\nwidth: 1px;\noutline: 0;\n-webkit-appearance: none;\n-moz-appearance: none;\n}\n\n    .edusharing_audio_wrapper {\n\tposition: relative;\n\theight: 350px;\n\tdisplay: flex;\n\toverflow: hidden;\n}\n.edusharing_audio_wrapper .edusharing_audio_bg {\n\tposition: absolute;\n\tleft: -25px;\n\tright: -25px;\n\ttop: 25px;\n\tbottom: 25px;\n\twidth: 100%;\n\theight: 100%;\n\tmargin: auto;\n\tobject-fit: cover;\n\tfilter: blur(25px) brightness(0.9);\n}\n.edusharing_audio_wrapper .edusharing_audio_img {\n\tdisplay: flex;\n\tposition: relative;\n\twidth: auto;\n\t/* max-width: 450px; */\n\tmargin: 20px 8% 75px 8%;\n\tbox-shadow: 0 0 9px rgba(0,0,0,.25);\n\tbackground: #fff;\n}\n.edusharing_audio_wrapper .edusharing_audio_img img {\n\twidth: 100%;\n\theight: 100%;\n\tobject-fit: cover;\n}\n.edusharing_audio_wrapper video {\n\tposition: absolute;\n\tbottom: 0;\n\twidth: 100%;\n\tbox-shadow: none;\n}</style>\n<div class=\"edusharing_rendering_content_footer\">\n    <div class=\"edusharing_rendering_content_footer_top\">\n        <a target=\"_blank\" href=\"https://www.brockhaus.de/portal/user/cid101882a?url=%2fjunior%2fecs%2f%2fkilex%2farticle%2fuganda\" class=\"edu_sharing_filename\">Uganda</a>        <div class=\"edusharing_metadata_wrapper\">\n   <i class=\"material-icons edusharing_metadata_toggle_button\">info_outline</i>\n\t<div class=\"edusharing_metadata\" style=\"display:none\">\n        <div class=\"edusharing_metadata_inner edusharing_rendering_metadata_body\">\n\t\t<div class='mdsGroup mdsGroup-node_general_render'><h2 class='mdsCaption node_general_render'>Allg. Informationen</h2><div class='mdsContent'><div data-widget-id='cclom:title' class='mdsWidget mdsWidget_text' caption=\"Titel\"><h3 class='mdsWidgetCaption'>Titel</h3><div class='mdsWidgetContent mds_cclom_title'><div class='mdsValue' data-value-key='Uganda'><div>Uganda</div></div></div></div><div data-widget-id='cclom:general_description' class='mdsWidget mdsWidget_text'><h3 class='mdsWidgetCaption'>Beschreibung</h3><div class='mdsWidgetContent mds_cclom_general_description'><div class='mdsValue' data-value-key='Uganda ist ein Staat im Osten Afrikas. Es ist ein Binnenstaat, der nicht am Meer liegt. Das Land grenzt an den S�dsudan, Kenia, Tansania, Ruanda und die Demokratische Republik Kongo. Es ist etwa zwei Drittel so gro� wie...'><div>Uganda ist ein Staat im Osten Afrikas. Es ist ein Binnenstaat, der nicht am Meer liegt. Das Land grenzt an den S�dsudan, Kenia, Tansania, Ruanda und die Demokratische Republik Kongo. Es ist etwa zwei Drittel so gro� wie...</div></div></div></div></div></div><div class='mdsGroup mdsGroup-node_contributor_render'><h2 class='mdsCaption node_contributor_render'>Lizenz & Beteiligte</h2><div class='mdsContent'><div data-widget-id='license' class='mdsWidget mdsWidget_license'><h3 class='mdsWidgetCaption'>Lizenz</h3><div class='mdsWidgetContent mds_license'><div class='mdsValue' data-value-key='-'><div><img src='https://repository.staging.cloud.schulcampus-rlp.de/edu-sharing/ccimages/licenses/none.svg' alt=\"\"><div class='licenseGroup'>Keine Lizenz gew�hlt</div><div class='licenseDescription'>Nutzung und Quellenangabe gem�� den im Medium genannten Bedingungen bzw. gem�� der allgemeing�ltigen gesetzlichen Regelung (UrhG).</div></div></div></div></div><div class=\"mdsContributorGroup\">\n\t\t\t\t\t<div id=\"mdsLifecyclecontributorsTitle\" class=\"mdsContributorTitle\">Mitarbeitende am Material</div>\n\t\t\t\t\t<div id=\"mdsLifecyclecontributors\"></div>\n               \t\t<div id=\"mdsMetadatcontributorsTitle\" class=\"mdsContributorTitle\">Mitarbeitende an Metadaten</div>\n               \t\t<div id=\"mdsMetadatcontributors\"></div>\n               \t</div>\n               \t<script>\n               \t\tfunction hideIfEmpty(toHide,isEmpty){\n               \t\t\tif(isEmpty.innerHTML.trim()==\"\"){\n               \t\t\t\ttoHide.style.display='none';\n               \t\t\t}\n               \t\t}\n               \t\thideIfEmpty(document.getElementById(\"mdsLifecyclecontributorsTitle\"),document.getElementById(\"mdsLifecyclecontributors\"));\n               \t\thideIfEmpty(document.getElementById(\"mdsMetadatcontributorsTitle\"),document.getElementById(\"mdsMetadatcontributors\"));\n               \t</script></div></div>        </div>\n\t</div>\n</div>\n\n<script src=\"https://rendering.services.staging.cloud.schulcampus-rlp.de:443/esrender/vendor/js/metadataToggler.js\"></script>\n    </div>\n    <div class=\"edusharing_rendering_content_footer_bot\">\n            </div>\n</div>\n",
  mimeType: 'application/xhtml+xml',
  node: {
    nodeLTIDeepLink: null,
    remote: {
      repository: {
        repositoryType: 'BROCKHAUS',
        renderingSupported: true,
        id: 'brockhaus',
        title: 'Brockhaus',
        icon: 'https://repository.staging.cloud.schulcampus-rlp.de/edu-sharing/assets/images/sources/brockhaus.png',
        logo: 'https://repository.staging.cloud.schulcampus-rlp.de/edu-sharing//edu-sharing/assets/images/sources/brockhaus.png',
        isHomeRepo: false,
      },
      id: '%2fkilex%2farticle%2fuganda',
    },
    content: {
      url: 'https://www.brockhaus.de/portal/user/cid101882a?url=%2fjunior%2fecs%2f%2fkilex%2farticle%2fuganda',
      hash: null,
      version: null,
    },
    license: {
      icon: 'https://repository.staging.cloud.schulcampus-rlp.de/edu-sharing/ccimages/licenses/none.svg',
      url: null,
    },
    isDirectory: false,
    commentCount: 0,
    rating: {
      overall: { sum: 0, count: 0, rating: 0 },
      affiliation: {},
      user: 0,
    },
    usedInCollections: [],
    relations: null,
    contributors: [],
    ref: {
      repo: 'local',
      id: '363a7662-cca1-4945-893b-088a8310dfa9',
      archived: false,
      isHomeRepo: true,
    },
    parent: {
      repo: 'local',
      id: null,
      archived: false,
      isHomeRepo: true,
    },
    type: 'ccm:remoteobject',
    aspects: [
      'ccm:eduscope',
      'ccm:usageaspect',
      'cm:auditable',
      'sys:referenceable',
      'sys:localized',
      'ccm:remoterepository',
    ],
    name: 'Uganda',
    title: 'Uganda',
    metadataset: null,
    repositoryType: 'ALFRESCO',
    createdAt: null,
    createdBy: {
      profile: null,
      firstName: null,
      lastName: null,
      mailbox: null,
    },
    modifiedAt: null,
    modifiedBy: {
      profile: null,
      firstName: null,
      lastName: null,
      mailbox: null,
    },
    access: ['Read', 'ReadAll', 'Feedback'],
    downloadUrl: null,
    properties: {
      'ccm:replicationsource': ['brockhaus'],
      'cclom:format': ['application/xhtml+xml'],
      'cclom:title': ['Uganda'],
      'cm:name': ['Uganda'],
      'virtual:mediatype': ['Website'],
      'virtual:type': ['ccm:remoteobject'],
      'ccm:wwwurl': [
        'https://www.brockhaus.de/portal/user/cid101882a?url=%2fjunior%2fecs%2f%2fkilex%2farticle%2fuganda',
      ],
      'cclom:general_description': [
        'Uganda ist ein Staat im Osten Afrikas. Es ist ein Binnenstaat, der nicht am Meer liegt. Das Land grenzt an den Südsudan, Kenia, Tansania, Ruanda und die Demokratische Republik Kongo. Es ist etwa zwei Drittel so groß wie...',
      ],
      'ccm:thumbnailurl': [
        'https://assets-cdn.brockhaus.de/image/small/1194793.jpg',
      ],
      'cm:modified': ['1712926792118'],
      'sys:node-uuid': ['%2fkilex%2farticle%2fuganda'],
    },
    mimetype: 'application/xhtml+xml',
    mediatype: 'link',
    size: null,
    preview: {
      isIcon: true,
      isGenerated: false,
      type: null,
      mimetype: null,
      data: null,
      url: 'https://repository.staging.cloud.schulcampus-rlp.de/edu-sharing/preview?nodeId=%252fkilex%252farticle%252fuganda&repository=brockhaus&storeProtocol=null&storeId=null&dontcache=1712926844013',
      width: null,
      height: null,
    },
    iconURL:
      'https://repository.staging.cloud.schulcampus-rlp.de/edu-sharing/themes/default/images/common/mime-types/svg/link.svg',
    collection: null,
    owner: null,
    isPublic: false,
  },
}
