export const videoEmbedJson = {
  detailsSnippet:
    "    \n<style>\n    \n.edusharing_rendering_metadata_body .mdsGroup{\n    flex: 1;\n    padding: 0 20px;\n    min-width: 25%;\n}\n.edusharing_rendering_metadata_body .mdsCaption{\n    border-bottom: 1px solid #6f6f6f;\n    color: #6f6f6f;\n    padding: 8px 15px;\n    font-size: 130%;\n    height: auto;\n    margin: 30px 0 0;\n    font-weight: normal;\n}\n.edusharing_rendering_metadata_body .mdsWidgetCaption{\n    display: block;\n    font-style: italic;\n    font-size: unset;\n    color: #6f6f6f;\n    margin: 15px 0 0 15px;\n    line-height: 1.5;\n}\n\n.edusharing_rendering_metadata_body .mdsWidget:not(.mdsWidget_tinyMCE)  .mdsWidgetContent{\n    white-space: pre-line;\n}\n.edusharing_rendering_metadata_body .mdsWidget_tinyMCE  .mdsValue > div > p:first-child {\n    margin-top: 0;\n}\n\n.edusharing_rendering_metadata_body .mdsWidgetContent .mdsValue{\n    display: inline-flex;\n    margin: 3px 0 0 15px;\n    line-height: 1.5;\n}\n.edusharing_rendering_metadata_body .mdsWidgetMultivalue{\n    margin: 5px 0 0 8px;\n}\n.edusharing_rendering_metadata_body .mdsWidgetMultivalue .mdsValue{\n    display: inline-block;\n    color: #383838;\n    background-color: #F4F4F4;\n    border-radius: 16px;\n    padding: 5px 10px;\n    margin-left: 10px;\n}\n\n.edusharing_rendering_metadata_body .mdsWidget_vcard .mdsValue {\n    display: inline-flex;\n    font-style: italic;\n}\n\n.edusharing_rendering_metadata_body .mdsWidgetContent .mdsValue > i {\n    font-size: 18px;\n    margin-right: 5px;\n    vertical-align: middle;\n}\n\n.edusharing_rendering_metadata_body .mdsWidgetContent .mdsValue > * {\n    margin: auto;\n}\n\n.edusharing_rendering_metadata_body .mdsContributorTitle {\n    font-weight: 600;\n    font-style: normal;\n    margin: 25px 0 -10px 0;\n    color: #000;\n}\n\n.edusharing_rendering_metadata_body .mdsContributorGroup .mdsWidgetCaption,\n.edusharing_rendering_metadata_body .mdsContributorGroup .mdsValue{\n    margin-left: 0;\n    margin-right: 10px;\n}\n\n/* Produce a proper bounding box for focus styles (not provided here). */\n.edusharing_rendering_metadata_body .mds_license a {\n    display: inline-flex;\n    flex-direction: column;\n    gap: 6px;\n}\n.edusharing_rendering_metadata_body .mds_license img {\n    height: 30px;\n    width: auto;\n}\n.edusharing_rendering_metadata_body .mds_license .licenseName {\n    font-weight: bold;\n}\n.edusharing_rendering_metadata_body .mds_license .licenseDescription {\n    color: #6f6f6f;\n    font-size: 90%;\n}\n\n.edusharing_rendering_metadata_body .mds_material_feedback{\n    background: #4D799A;\n    width: 60%;\n    max-width: 220px;\n    margin: 16px auto 8px;\n    border-radius: 3px;\n    box-shadow: 2px 2px 4px 0px rgba(0,0,0,0.25);\n    transition: 0.5s ease-in-out;\n}\n\n.edusharing_rendering_metadata_body .mds_material_feedback .mdsValue{\n    width: 100%;\n    margin: 4px auto;\n}\n\n.edusharing_rendering_metadata_body .mds_material_feedback a{\n    color: #fff;\n    font-weight: 500;\n    display: flex;\n    justify-content: center;\n    padding: 4px 0;\n}\n.edusharing_rendering_metadata_body .mds_material_feedback a:hover,\n.edusharing_rendering_metadata_body .mds_material_feedback a:visited{\n    color: #fff;\n    text-decoration: none;\n}\n\n.edusharing_rendering_metadata_body .mds_material_feedback a i{\n    padding-right: 8px;\n}\n\n\n@media (max-width: 1400px) {\n    .edusharing_rendering_metadata_body .mdsGroup{\n        min-width:50%;\n    }\n}\n\n@media (max-width: 700px) {\n    .edusharing_rendering_metadata_body {\n        display: block;\n    }\n\n    .edusharing_rendering_metadata_body .mdsGroup {\n        display: block;\n        padding: 0;\n    }\n}\n\n@font-face {\nfont-family: 'Material Icons';\nfont-style: normal;\nfont-weight: 400;\nsrc: url('https://rendering.services.staging.cloud.schulcampus-rlp.de:443/esrender/vendor/fonts/materialicons/MaterialIcons-Regular.eot'); /* For IE6-8 */\nsrc: local('Material Icons'),\nlocal('MaterialIcons-Regular'),\nurl('https://rendering.services.staging.cloud.schulcampus-rlp.de:443/esrender/vendor/fonts/materialicons/MaterialIcons-Regular.woff2') format('woff2'),\nurl('https://rendering.services.staging.cloud.schulcampus-rlp.de:443/esrender/vendor/fonts/materialicons/MaterialIcons-Regular.woff') format('woff'),\nurl('https://rendering.services.staging.cloud.schulcampus-rlp.de:443/esrender/vendor/fonts/materialicons/MaterialIcons-Regular.ttf') format('truetype');\n}\n\n.edusharing_rendering_content_wrapper {\nmin-width: 300px;\nline-height: 1.2;\n}\n.edusharing_rendering_content_video_options_container_expanded {\nbackground: rgba(0, 0, 0, 0.6);\n}\ndiv.edusharing_rendering_content_video_options {\nposition: absolute;\ntop: 2%;\nright: 2%;\ncolor: #fff;\nmargin: 0;\npadding: 5px;\ntext-align: right;\n}\n.edusharing_rendering_content_video_options_container {\ndisplay: flex;\nflex-direction: column;\nalign-items: flex-end;\nposition: absolute;\ntop: 2%;\nright: 2%;\ncolor: #fff;\nmargin: 0;\ntext-align: right;\n}\n.edusharing_rendering_content_video_options {\ndisplay: flex;\nbackground: none;\nborder: none;\ncolor: #fff;\npadding: 5px;\ncursor: pointer;\n}\n\ndiv.edusharing_rendering_content_video_options i {\nopacity: 0.8;\ncursor: pointer;\n}\n\ndiv.edusharing_rendering_content_video_options_content {\ndisplay: none;\n}\n\n.edusharing_rendering_content_video_options_container_expanded .edusharing_rendering_content_video_options_content {\ndisplay: block;\n}\n\ndiv.edusharing_rendering_content_video_wrapper {\ndisplay: inline-block;\nposition: relative;\n}\n\ndiv.edusharing_rendering_content_video_wrapper:hover div.edusharing_rendering_content_video_options {\ndisplay: block;\n}\n\nul.edusharing_rendering_content_video_options_resolutions {\npadding: 0;\nmargin: 0;\nfont-size: 18px !important;\n}\n\nul.edusharing_rendering_content_video_options_resolutions i {\nvertical-align: middle;\nmargin-right: 10px;\nfont-size: 18px !important;\n}\n\ni.edusharing_rendering_content_video_options_toggle {\ntext-shadow: 0px 0px 4px #333;\n}\n\nul.edusharing_rendering_content_video_options_resolutions > li {\ncursor: pointer;\npadding: 4px 0;\nlist-style: none;\n}\n\nul.edusharing_rendering_content_video_options_resolutions > li.edusharing_rendering_content_video_options_resolutions_converting {\ncolor: #999999\n}\n\n.material-icons {\nfont-family: 'Material Icons';\nfont-weight: normal;\nfont-style: normal;\nfont-size: 24px;  /* Preferred icon size */\ndisplay: inline-block;\nline-height: 1;\ntext-transform: none;\nletter-spacing: normal;\nword-wrap: normal;\nwhite-space: nowrap;\ndirection: ltr;\n\n/* Support for all WebKit browsers. */\n-webkit-font-smoothing: antialiased;\n/* Support for Safari and Chrome. */\ntext-rendering: optimizeLegibility;\n\n/* Support for Firefox. */\n-moz-osx-font-smoothing: grayscale;\n\n/* Support for IE. */\nfont-feature-settings: 'liga';\n}\n\n.edusharing_metadata_wrapper {\nmargin-left: 10px;\n}\n\n.edusharing_metadata_toggle_button {\nwidth: 30px; height: 30px; display: inline-block;\nborder-left: 1px solid #cdcdcd;\npadding-left: 5px;\ncursor:pointer;\npadding-top: 3px;\ncolor: #4D799A;\ntransition: ease-in-out 0.3s;\n}\n\n.edusharing_metadata_toggle_button:hover {\ncolor: #00a0d2;\n}\n\n.edusharing_metadata {\nposition: absolute;\nmargin-top: 4px;\nmargin-left: -295px;\nwidth: 350px;\npadding: 11px 0px;\nz-index: 50;\n}\n\n.edusharing_metadata_inner {\ndisplay: flex;\nflex-direction: column;\nalign-items: center;\njustify-content: space-between;\nbackground-color: #f6f6f6;\nborder: 1px solid #ddd;\nborder-radius: 6px;\nbox-shadow: 2px 2px 6px rgba(0, 0, 0, .2);\nmax-height:500px;\noverflow-y: auto;\nfont-size: .9em;\nline-height: 1;\ntransition: ease-in-out 0.3s;\n}\n\n.edusharing_metadata_inner img {\nheight: 16px;\n}\n\n.edusharing_metadata_inner .mdsGroup .mdsCaption {\nfont-size: 1.5em;\nheight: auto;\npadding-bottom: 10px;\nmargin: 0;\n}\n\n.edusharing_rendering_metadata_body .mdsCaption{\nborder-bottom: 1px solid #777 !important;\ncolor: #777 !important;\npadding: 0 12px !important;\nmargin-top: 0 !important;\n}\n\n.edusharing_metadata:before {\nborder-bottom: 15px solid #ddd;\nborder-left: 15px solid transparent;\nborder-right: 15px solid transparent;\ntop: -4px;\ncontent: \"\";\nposition: absolute;\nright: 23px;\nwidth: 0;\nheight: 0;\n}\n\n.edusharing_metadata:after {\nborder-bottom: 15px solid #f6f6f6;\nborder-left: 15px solid transparent;\nborder-right: 15px solid transparent;\ntop: -3px;\ncontent: \"\";\nposition: absolute;\nright: 23px;\nwidth: 0;\nheight: 0;\n}\n\n.mdsGroup {\nbackground: #fff;\nmargin: 8px;\npadding: 12px 0;\nborder: 1px solid #ddd;\n}\n\n.mdsGroup .mdsWidget {\ndisplay: flex;\nflex-wrap: wrap;\nalign-items: baseline;\n}\n\n.mdsGroup .mdsWidget .mdsWidgetCaption {\ncolor: #aaa;\nfont-weight: 500;\n}\n\n.edusharing_rendering_metadata_body .mdsGroup{\nwidth: 94%;\npadding: 12px 0;\nborder-radius: 4px;\n}\n\n.edusharing_rendering_metadata_body .licenseName {\nmargin-top: 8px;\n}\n\n.edusharing_rendering_metadata_body .mdsContributorTitle {\nmargin: 0 !important;\nmargin-top: 25px !important;\n}\n\n.mdsGroup:first-child {\n\n}\n\n.edusharing_metadata_inner .mdsGroup .mdsContributorGroup {\nmargin-left: 15px;\n}\n\n.edusharing_warning {\ndisplay: inline-block;\nbackground-color: #c6c6c6;\ncolor: #383838;\npadding: 5px;\nborder-radius: 3px;\n}\n\n.edusharing_rendering_content_footer {\nwidth: 100%;\nbackground: #f6f6f6;\npadding: 6px;\n}\n\n.edusharing_rendering_content_footer a, .edusharing_rendering_content_footer a:visited, .edusharing_rendering_content_footer a:focus, .edusharing_rendering_content_footer a:hover {\ncolor: #4D799A;\n}\n\n.edusharing_rendering_content_footer_top {\noverflow-y: hidden;\noverflow-x: hidden;\ndisplay: flex;\nalign-items: center;\njustify-content: space-between;\nmin-height: 2rem;\n}\n\n.edusharing_rendering_content_footer_bot {\n}\n\n.edusharing_rendering_content_footer_metadata {\nwidth: 30px;\npadding: 10px;\n}\n\n.edusharing_rendering_content_footer_sequence {\nposition: relative;\n\n}\n\n.edusharing_rendering_content_footer_directory {\nwidth: 100%;\nbackground: #f6f6f6;\npadding: 12px;\n}\n\n.edusharing_rendering_content_footer_directory_img{\nmax-height: 33px;\n}\n\n.edusharing_rendering_content_footer_directory_header {\ndisplay: flex;\nalign-items: center;\njustify-content: space-between;\n}\n\n.edusharing_rendering_content_footer_directory_header a {\ncolor: #4D799A;\n}\n\n.edusharing_rendering_content_footer_directory_header a:hover {\ntext-decoration: none;\n}\n\n.edusharing_rendering_content_footer_directory_toggle > * {\nmargin-right: 20px;\n}\n\n.edusharing_rendering_content_footer_directory_creator {\ndisplay:block;\ncolor: #999;\nfont-size: 90%;\n}\n\n.edusharing_rendering_content_footer_sequence .material-icons {\nvertical-align: middle !important;\n}\n\n.edusharing_rendering_content_footer_directory .material-icons {\nvertical-align: middle !important;\n}\n\n.edusharing_rendering_content_footer_sequence_toggle, .edusharing_rendering_content_footer_directory_toggle {\ncolor: #4D799A;\ncursor:pointer;\ndisplay: flex;\nalign-items: center;\n}\n\n.edusharing_rendering_content_footer_sequence_toggle {\nmargin-top: 6px;\n}\n\n.edusharing_rendering_content_footer_directory_toggle {\ndisplay: flex;\nalign-items: center;\nwidth: 100%;\n}\n\n.edusharing_rendering_content_footer_sequence ul {\npadding: 12px;\nposition: absolute;\nz-index: 49;\nbackground: #f6f6f6;\nwidth: calc(100% + 12px);\nmargin-left: -6px;\n}\n\n.edusharing_rendering_content_footer_directory ul {\nmargin: 10px 0 0 0;\nbackground: #f6f6f6;\nwidth: 100%;\npadding: 0 !important;\n}\n\n.edusharing_rendering_content_footer_sequence ul li, .edusharing_rendering_content_footer_directory ul li {\nlist-style: none;\nheight: 60px;\nbackground: #fff;\nfont-size: 14px;\nmargin: 3px 0;\ndisplay: flex;\nalign-items: center;\nwidth: 100%;\nborder-radius: 3px;\n}\n\n.edusharing_rendering_content_footer_sequence ul li a, .edusharing_rendering_content_footer_directory ul li a {\ndisplay: flex;\nalign-items: center;\ncolor: #383838;\ntext-decoration: none;\nwidth: 100%;\n}\n\n.edusharing_rendering_content_footer_sequence ul li a:hover, .edusharing_rendering_content_footer_directory ul li a:hover {\ncolor: #383838;\ntext-decoration: none;\n}\n\n.edusharing_rendering_content_footer_sequence ul li img, .edusharing_rendering_content_footer_directory ul li img {\nmargin: 10px;\n}\n\n.edusharing_rendering_content_footer_sequence_showall {\nmargin-bottom: 0;\ntext-align: right;\ndisplay: inline-block;\nwidth: 100%;\nmargin-top: 8px;\n}\n\n.edusharing_rendering_content_footer_top .license_permalink, .edusharing_rendering_content_footer_top .license {\nmargin-right: 40px;\n}\n\nvideo, audio {\nmargin-bottom: -6px;\nborder: 0;\n}\n\n.edu_audio_wrapper{\ndisplay: inline-block;\nmin-width: 70%;\n}\n\n.dataProtectionRegulations {\nposition: relative;\naspect-ratio: 16 / 9;\nmax-width: 800px;\n}\n.dataProtectionRegulations, .dataProtectionRegulationsDialog {\nbackground: #fff;\npadding: 20px;\n-webkit-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.3);\n-moz-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.3);\nbox-shadow: 0px 2px 3px 0px rgba(0,0,0,0.3);\ntext-align: center;\nbackground: #f6f6f6;\nmargin: auto;\nborder: 0;\n}\n.dataProtectionRegulations .dataProtectionRegulationsContainer {\nposition: absolute;\nwidth: 100%;\nz-index: 1;\ncolor: #fff !important;\ntext-shadow: 0 0 5px rgba(0,0,0,.5);\npadding: 15px 20px;\nbackdrop-filter: blur(4px);\nbackground-color: rgba(0,0,0,.6);\nleft: 0;\nbottom: 0;\n}\n.dataProtectionRegulations .dataProtectionRegulationsContainer p{\ncolor: #fff !important;\n}\n.dataProtectionRegulations .dataProtectionRegulationsContainer a:not(.btn) {\ncolor: #B6D8FC;\ntext-decoration: underline;\n}\n.dataProtectionRegulations .dataProtectionVideoBg {\nposition: absolute;\nleft: 0;\ntop: 0;\nobject-fit: cover;\nwidth: 100%;\nheight: 100%;\n}\n\n.dataProtectionRegulationsHeading {\nfont-size: 1.6em;\n}\n\na.edusharing_rendering_content {\nmargin-top: 20px;\nmargin-left: 10px;\nmargin-right: 10px;\n}\n\n.cdk-visually-hidden {\nborder: 0;\nclip: rect(0 0 0 0);\nheight: 1px;\nmargin: -1px;\noverflow: hidden;\npadding: 0;\nposition: absolute;\nwidth: 1px;\noutline: 0;\n-webkit-appearance: none;\n-moz-appearance: none;\n}\n\n</style>\n<div class=\"edusharing_rendering_content_video_wrapper\">\n    <video src=\"https://rendering.services.staging.cloud.schulcampus-rlp.de:443/esrender/modules/cache/video/2024/03/25/12/57/34/5519f192-639a-47c9-bb6e-b580dd2d9ad3_1.0_720.mp4?ESSID=h3q0a9vfp8nengqebda4f9pb6v&token=d2460de45288f58a4ab64532a47e06a1\" style=\"max-width: 100%;\" data-tap-disabled=\"true\" id=\"v_660174f80b5d9\" data-licid=\"660174f80b669\" controls controlsList=\"nodownload\" oncontextmenu=\"return false;\"></video>\n    <div id=\"edusharing_rendering_content_video_options_container_v_660174f80b5d9\" class=\"edusharing_rendering_content_video_options_container\">\n        <button id=\"edusharing_rendering_content_video_options_buttonv_660174f80b5d9\" class=\"edusharing_rendering_content_video_options\" aria-label=\"Video-Auflösung wählen\" aria-haspopup=\"true\">\n            <i class=\"material-icons edusharing_rendering_content_video_options_toggle\">settings</i>\n        </button>\n        <div class=\"edusharing_rendering_content_video_options_content\">\n            <ul role=\"menu\" id=\"edusharing_rendering_content_video_options_resolutions_v_660174f80b5d9\" class=\"edusharing_rendering_content_video_options_resolutions\" aria-labelledby=\"edusharing_rendering_content_video_options_buttonv_660174f80b5d9\">\n                <li role=\"menuitemradio\" aria-checked=\"false\" tabindex=\"0\" class=\"option_v_660174f80b5d9\" id=\"option_v_660174f80b5d9-240\" data-url=\"https://rendering.services.staging.cloud.schulcampus-rlp.de:443/esrender/modules/cache/video/2024/03/25/12/57/34/5519f192-639a-47c9-bb6e-b580dd2d9ad3_1.0_240.mp4?ESSID=h3q0a9vfp8nengqebda4f9pb6v&token=d2460de45288f58a4ab64532a47e06a1\">240p</li><li role=\"menuitemradio\" aria-checked=\"true\" tabindex=\"0\" class=\"option_v_660174f80b5d9\" id=\"option_v_660174f80b5d9-720\" data-url=\"https://rendering.services.staging.cloud.schulcampus-rlp.de:443/esrender/modules/cache/video/2024/03/25/12/57/34/5519f192-639a-47c9-bb6e-b580dd2d9ad3_1.0_720.mp4?ESSID=h3q0a9vfp8nengqebda4f9pb6v&token=d2460de45288f58a4ab64532a47e06a1\"><i class=\"material-icons\" aria-hidden=\"true\">done</i>720p</li>            </ul>\n        </div>\n    </div>\n    <div class=\"edusharing_rendering_content_footer\">\n    <div class=\"edusharing_rendering_content_footer_top\">\n        <a class=\"license_permalink\" href=\"{{{LMS_INLINE_HELPER_SCRIPT}}}&closeOnBack=true\" target=\"_blank\" title=\"Lars Testvideo\"><es:title xmlns:es=\"http://edu-sharing.net/object\" >Lars Testvideo</es:title></a>        <div class=\"edusharing_metadata_wrapper\">\n   <i class=\"material-icons edusharing_metadata_toggle_button\">info_outline</i>\n\t<div class=\"edusharing_metadata\" style=\"display:none\">\n        <div class=\"edusharing_metadata_inner edusharing_rendering_metadata_body\">\n\t\t<div class='mdsGroup mdsGroup-node_general_render'><h2 class='mdsCaption node_general_render'>Allg. Informationen</h2><div class='mdsContent'><div data-widget-id='cclom:title' class='mdsWidget mdsWidget_text' caption=\"Titel\"><h3 class='mdsWidgetCaption'>Titel</h3><div class='mdsWidgetContent mds_cclom_title'><div class='mdsValue' data-value-key='Lars Testvideo'><div>Lars Testvideo</div></div></div></div></div></div><div class='mdsGroup mdsGroup-node_contributor_render'><h2 class='mdsCaption node_contributor_render'>Lizenz & Beteiligte</h2><div class='mdsContent'><div data-widget-id='license' class='mdsWidget mdsWidget_license'><h3 class='mdsWidgetCaption'>Lizenz</h3><div class='mdsWidgetContent mds_license'><div class='mdsValue' data-value-key='-'><div><img src='https://repository.staging.cloud.schulcampus-rlp.de/edu-sharing/ccimages/licenses/none.svg' alt=\"\"><div class='licenseGroup'>Keine Lizenz gewählt</div><div class='licenseDescription'>Nutzung und Quellenangabe gemäß den im Medium genannten Bedingungen bzw. gemäß der allgemeingültigen gesetzlichen Regelung (UrhG).</div></div></div></div></div><div class=\"mdsContributorGroup\">\n\t\t\t\t\t<div id=\"mdsLifecyclecontributorsTitle\" class=\"mdsContributorTitle\">Mitarbeitende am Material</div>\n\t\t\t\t\t<div id=\"mdsLifecyclecontributors\"></div>\n               \t\t<div id=\"mdsMetadatcontributorsTitle\" class=\"mdsContributorTitle\">Mitarbeitende an Metadaten</div>\n               \t\t<div id=\"mdsMetadatcontributors\"><div data-widget-id='ccm:metadatacontributer_creator' class='mdsWidget mdsWidget_vcard'><h3 class='mdsWidgetCaption'>Ersteller*in</h3><ul class='mdsWidgetContent mds_ccm_metadatacontributer_creator mdsWidgetMultivalue'><li class='mdsValue' data-value-key='BEGIN:VCARD\nVERSION:3.0\nUID:urn:uuid:ca43354b-2aae-4ede-9fb6-0a565ae91d5b\nN:schuelereins;sso\nFN:sso schuelereins\nORG:\nURL:\nTITLE:\nTEL;TYPE&#61;WORK,VOICE:\nADR;TYPE&#61;intl,postal,parcel,work:;;;;;;\nEMAIL;TYPE&#61;PREF,INTERNET:dennis.hakenbeck2&#64;pl.rlp.de\nEND:VCARD\n'><i class='material-icons'>person</i><div>sso schuelereins</div></li></ul></div></div>\n               \t</div>\n               \t<script>\n               \t\tfunction hideIfEmpty(toHide,isEmpty){\n               \t\t\tif(isEmpty.innerHTML.trim()==\"\"){\n               \t\t\t\ttoHide.style.display='none';\n               \t\t\t}\n               \t\t}\n               \t\thideIfEmpty(document.getElementById(\"mdsLifecyclecontributorsTitle\"),document.getElementById(\"mdsLifecyclecontributors\"));\n               \t\thideIfEmpty(document.getElementById(\"mdsMetadatcontributorsTitle\"),document.getElementById(\"mdsMetadatcontributors\"));\n               \t</script></div></div>        </div>\n\t</div>\n</div>\n    </div>\n    <div class=\"edusharing_rendering_content_footer_bot\">\n            </div>\n</div>\n    <p id=\"e_v_660174f80b5d9\" style=\"display: none;\">Der Videoplayer kann dieses Video nicht wiedergeben.</p>\n</div>\n\n<script>\n    (() => {\n        const menuContainerSelector = '#edusharing_rendering_content_video_options_container_v_660174f80b5d9';\n        const menuButtonSelector = '#edusharing_rendering_content_video_options_buttonv_660174f80b5d9';\n\n        const timeStamps = window.location.hash.substring(1);\n        if (timeStamps !== \"\") {\n            const video = document.getElementById('v_660174f80b5d9');\n            video.src = video.src + '#' + timeStamps;\n        }\n\n        $('.option_v_660174f80b5d9').click(function() {\n            onOptionClick(this);\n        });\n        $('#edusharing_rendering_content_video_options_buttonv_660174f80b5d9').on(\"click\", function() {\n            $(this).parent().find('.edusharing_rendering_content_video_options_content').toggle();\n        });\n\n        $('.option_v_660174f80b5d9').keydown((event) => {\n            switch (event.code) {\n                case 'Enter':\n                    onOptionClick(event.target);\n                    event.preventDefault();\n                    break;\n                case 'ArrowUp':\n                    $(event.target).prev().focus();\n                    event.preventDefault();\n                    break;\n                case 'ArrowDown':\n                    $(event.target).next().focus();\n                    event.preventDefault();\n                    break;\n                case 'Escape':\n                    closeMenu();\n                    $(menuButtonSelector).focus();\n                    event.preventDefault();\n                    break;\n                case 'Tab':\n                    closeMenu();\n                    $(menuButtonSelector).focus();\n                    /* Don't call `preventDefault`, so the tab action is executed as if the menu\n                     button had the focus at the time of the key press and the menu was collapsed. */\n                    break;\n            }\n        });\n\n        let removeOutsideClickHandler;\n\n        function onOptionClick(element) {\n            var url = $(element).attr('data-url');\n            if (url == undefined)\n                return;\n            const selectedOption = $(element).parent().find('[aria-checked=\"true\"]');\n            selectedOption.find('i.material-icons').remove();\n            selectedOption.attr('aria-checked', 'false');\n            $(element).prepend('<i class=\"material-icons\" aria-hidden=\"true\">done</i>');\n            $(element).attr('aria-checked', 'true');\n            const video = document.getElementById('v_660174f80b5d9');\n            video.pause();\n            video.setAttribute('src', url + '#t=' + Math.ceil(video.currentTime)); /* ie not working */\n            video.load();\n            video.play();\n            closeMenu();\n            setTimeout(() => { /* Don't trigger another button click */\n                $(menuButtonSelector).focus();\n            });\n        }\n\n        function openMenu() {\n            const button = $(menuButtonSelector);\n            const container = $(menuContainerSelector);\n            button.attr('aria-expanded', 'true');\n            button.attr('aria-controls', 'edusharing_rendering_content_video_options_resolutions_v_660174f80b5d9');\n            container.addClass('edusharing_rendering_content_video_options_container_expanded');\n            setTimeout(() => {\n                $('.option_v_660174f80b5d9[aria-checked=\"true\"')[0].focus();\n                registerCloseMenuOnOutsideClick();\n            });\n        }\n\n        function closeMenu() {\n            const button = $(menuButtonSelector);\n            const container = $(menuContainerSelector);\n            button.removeAttr('aria-expanded');\n            button.removeAttr('aria-controls');\n            container.removeClass('edusharing_rendering_content_video_options_container_expanded');\n            if (removeOutsideClickHandler) {\n                removeOutsideClickHandler();\n            }\n        }\n\n        function registerCloseMenuOnOutsideClick() {\n            function handleClick(event) {\n                if (!isInsideOptionsMenu(event.target)) {\n                    closeMenu();\n                }\n            }\n            document.body.addEventListener('click', handleClick);\n            removeOutsideClickHandler = () => document.body.removeEventListener('click', handleClick);\n        }\n\n        function isInsideOptionsMenu(element) {\n            return $(element).closest(menuContainerSelector).length > 0;\n        }\n\n        function setResByConnection() {\n            /* navigator.connection not yet supported by all browsers, so check it first */\n            if (!navigator.connection) {\n                return;\n            }\n\n            const downLink = navigator.connection.downlink;\n\n            let resolution = '240';\n            if (downLink >= 5) {\n                resolution = '1080';\n            } else if (downLink >= 2) {\n                /* VIDEO_DEFAULT_RESOLUTION is already set, so we can skip the rest */\n                return;\n            }\n\n            const option = '#option_v_660174f80b5d9-' + resolution;\n            const url = $(option).attr('data-url');\n            if (url != undefined) {\n                const selectedOption = $(option).parent().find('[aria-checked=\"true\"]');\n                selectedOption.find('i.material-icons').remove();\n                selectedOption.attr('aria-checked', 'false');\n                $(option).prepend('<i class=\"material-icons\" aria-hidden=\"true\">done</i>');\n                $(option).attr('aria-checked', 'true');\n                var video_v_660174f80b5d9 = document.getElementById('v_660174f80b5d9');\n                video_v_660174f80b5d9.pause();\n                video_v_660174f80b5d9.setAttribute('src', url + '#t=' + Math.ceil(video_v_660174f80b5d9.currentTime)); /* ie not working */\n                video_v_660174f80b5d9.load();\n            }\n        }\n\n        $(document).ready(function() {\n            setResByConnection();\n        });\n\n        document.getElementById('v_660174f80b5d9').addEventListener('error', function(e) {\n            document.getElementById('b_v_660174f80b5d9').style.display = 'none';\n            switch (e.target.error.code) {\n                case e.target.error.MEDIA_ERR_ABORTED:\n                case e.target.error.MEDIA_ERR_NETWORK:\n                case e.target.error.MEDIA_ERR_DECODE:\n                case e.target.error.MEDIA_ERR_SRC_NOT_SUPPORTED:\n                    document.getElementById('v_660174f80b5d9').style.display = 'none';\n                    document.getElementById('e_v_660174f80b5d9').style.display = 'block';\n                    break;\n                default:\n                    return;\n            }\n        }, true);\n\n        function trackError() {\n            var url = 'https://rendering.services.staging.cloud.schulcampus-rlp.de:443/esrender/log/scr/clientlog.php';\n            var data = '%2Fvar%2Fcache%2Fesrender%2Fdata%2Fvideo%2F2024%2F03%2F25%2F12%2F57%2F34%2F5519f192-639a-47c9-bb6e-b580dd2d9ad3_1.0_.mp4';\n            try {\n                x = new(this.XMLHttpRequest || ActiveXObject)('MSXML2.XMLHTTP.3.0');\n                x.open(data ? 'POST' : 'GET', url, 1);\n                x.setRequestHeader('X-Requested-With', 'XMLHttpRequest');\n                x.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');\n                x.send(data)\n            } catch (e) {\n                window.console && console.log(e);\n            }\n        };\n    })();\n</script>",
  mimeType: 'video/mp4',
  node: {
    nodeLTIDeepLink: null,
    remote: null,
    content: {
      url: 'https://repository.staging.cloud.schulcampus-rlp.de/edu-sharing/components/render/5519f192-639a-47c9-bb6e-b580dd2d9ad3',
      hash: '1467485221',
      version: '1.1',
    },
    license: {
      icon: 'https://repository.staging.cloud.schulcampus-rlp.de/edu-sharing/ccimages/licenses/none.svg',
      url: null,
    },
    isDirectory: false,
    commentCount: 0,
    rating: {
      overall: { sum: 0, count: 0, rating: 0 },
      affiliation: {},
      user: 0,
    },
    usedInCollections: [],
    relations: null,
    contributors: [
      {
        property: 'ccm:metadatacontributer_creator',
        firstname: 'sso',
        lastname: 'schuelereins',
        email: 'VCARD_EMAIL',
        vcard:
          'BEGIN:VCARD\nVERSION:3.0\nUID:urn:uuid:ca43354b-2aae-4ede-9fb6-0a565ae91d5b\nN:schuelereins;sso\nFN:sso schuelereins\nORG:\nURL:\nTITLE:\nTEL;TYPE=WORK,VOICE:\nADR;TYPE=intl,postal,parcel,work:;;;;;;\nEMAIL;TYPE=PREF,INTERNET:dennis.hakenbeck2@pl.rlp.de\nEND:VCARD\n',
        org: '',
      },
    ],
    ref: {
      repo: 'local',
      id: '5519f192-639a-47c9-bb6e-b580dd2d9ad3',
      archived: false,
      isHomeRepo: true,
    },
    parent: {
      repo: 'local',
      id: '80829653-a0f7-4f79-96a3-d0a7fdb714f4',
      archived: false,
      isHomeRepo: true,
    },
    type: 'ccm:io',
    aspects: [
      'cclom:lifecycle',
      'ccm:eduscope',
      'cclom:technical',
      'ccm:iometadata',
      'cm:versionable',
      'ccm:tracking',
      'ccm:usageaspect',
      'sys:referenceable',
      'sys:localized',
      'cm:thumbnailModification',
      'cclom:schema',
      'cm:metadataset',
      'ccm:licenses',
      'ccm:commonlicenses',
      'cclom:rights',
      'cm:thumbnailed',
      'cm:auditable',
      'ccm:lomreplication',
      'cclom:meta-metadata',
      'cclom:general',
      'ccm:educontext',
    ],
    name: 'Lars Testvideo.mp4',
    title: 'Lars Testvideo',
    metadataset: 'mds',
    repositoryType: 'ALFRESCO',
    createdAt: '2024-03-25T12:57:29Z',
    createdBy: {
      profile: null,
      firstName: 'sso',
      lastName: 'schuelereins',
      mailbox: null,
    },
    modifiedAt: '2024-03-25T12:57:46Z',
    modifiedBy: {
      profile: null,
      firstName: 'sso',
      lastName: 'schuelereins',
      mailbox: null,
    },
    access: ['Read', 'ReadAll', 'Feedback'],
    downloadUrl:
      'https://repository.staging.cloud.schulcampus-rlp.de/edu-sharing/eduservlet/download?nodeId=5519f192-639a-47c9-bb6e-b580dd2d9ad3',
    properties: {
      'ccm:original': ['5519f192-639a-47c9-bb6e-b580dd2d9ad3'],
      'cm:created': ['1711371449666'],
      'virtual:commentcount': ['0'],
      'ccm:metadatacontributer_creatorVCARD_ORG': [''],
      'cclom:size': ['70424'],
      'cclom:version': ['1.1'],
      'virtual:usagecount': ['1'],
      'sys:node-uuid': ['5519f192-639a-47c9-bb6e-b580dd2d9ad3'],
      'virtual:childobjectcount': ['0'],
      'cclom:title': ['Lars Testvideo'],
      'virtual:mediatype': ['Video'],
      'sys:store-protocol': ['workspace'],
      'sys:store-identifier': ['SpacesStore'],
      'ccm:version_comment': ['METADATA_UPDATE'],
      'cclom:format': ['video/mp4'],
      'ccm:metadatacontributer_creatorVCARD_URL': [''],
      'ccm:create_version': ['true'],
      'cm:modifiedISO8601': ['2024-03-25T12:57:46.633Z'],
      'ccm:metadatacontributer_creatorVCARD_REGION': [''],
      'sys:node-dbid': ['49719526'],
      'cm:edu_metadataset': ['mds'],
      'ccm:metadatacontributer_creatorVCARD_PLZ': [''],
      'cm:creator': ['15407f04-cf8b-4937-a831-b2ac0c71b512'],
      'cm:autoVersion': ['false'],
      'virtual:permalink': [
        'https://repository.staging.cloud.schulcampus-rlp.de/edu-sharing/components/render/5519f192-639a-47c9-bb6e-b580dd2d9ad3/1.1',
      ],
      'ccm:metadatacontributer_creatorVCARD_GIVENNAME': ['sso'],
      'cm:versionLabel': ['1.1'],
      'ccm:search_context': ['campus_content'],
      'cm:versionable': ['true'],
      'ccm:metadatacontributer_creatorVCARD_COUNTRY': [''],
      'cm:created_LONG': ['1711371449666'],
      'virtual:primaryparent_nodeid': ['80829653-a0f7-4f79-96a3-d0a7fdb714f4'],
      'cm:lastThumbnailModification': ['imgpreview:1711371460502'],
      'ccm:metadatacontributer_creator': [
        'BEGIN:VCARD\nVERSION:3.0\nUID:urn:uuid:ca43354b-2aae-4ede-9fb6-0a565ae91d5b\nN:schuelereins;sso\nFN:sso schuelereins\nORG:\nURL:\nTITLE:\nTEL;TYPE=WORK,VOICE:\nADR;TYPE=intl,postal,parcel,work:;;;;;;\nEMAIL;TYPE=PREF,INTERNET:dennis.hakenbeck2@pl.rlp.de\nEND:VCARD\n',
      ],
      'ccm:metadatacontributer_creatorVCARD_TEL': [''],
      'ccm:metadatacontributer_creatorVCARD_STREET': [''],
      'cm:createdISO8601': ['2024-03-25T12:57:29.666Z'],
      'cm:modified': ['1711371466633'],
      'cm:edu_forcemetadataset': ['false'],
      'ccm:metadatacontributer_creatorVCARD_CITY': [''],
      'cm:modifier': ['15407f04-cf8b-4937-a831-b2ac0c71b512'],
      'cm:autoVersionOnUpdateProps': ['false'],
      'cclom:location': ['ccrep://local/5519f192-639a-47c9-bb6e-b580dd2d9ad3'],
      'ccm:educontextname': ['default'],
      'ccm:metadatacontributer_creatorVCARD_EMAIL': [
        'dennis.hakenbeck2@pl.rlp.de',
      ],
      'ccm:metadatacontributer_creatorFN': ['sso schuelereins'],
      'cm:modified_LONG': ['1711371466633'],
      'ccm:metadatacontributer_creatorVCARD_TITLE': [''],
      'cm:automaticUpdate': ['true'],
      'cm:name': ['Lars Testvideo.mp4'],
      'virtual:type': ['ccm:io'],
      'ccm:search_context_DISPLAYNAME': ['Campus Inhalt'],
      'cm:initialVersion': ['false'],
      'ccm:metadatacontributer_creatorVCARD_SURNAME': ['schuelereins'],
    },
    mimetype: 'video/mp4',
    mediatype: 'file-video',
    size: '70424',
    preview: {
      isIcon: false,
      isGenerated: true,
      type: 'TYPE_GENERATED',
      mimetype: null,
      data: null,
      url: 'https://repository.staging.cloud.schulcampus-rlp.de/edu-sharing/preview?nodeId=5519f192-639a-47c9-bb6e-b580dd2d9ad3&storeProtocol=workspace&storeId=SpacesStore&dontcache=1711371512089',
      width: null,
      height: null,
    },
    iconURL:
      'https://repository.staging.cloud.schulcampus-rlp.de/edu-sharing/themes/default/images/common/mime-types/svg/file-video.svg',
    collection: null,
    owner: {
      profile: null,
      firstName: 'sso',
      lastName: 'schuelereins',
      mailbox: null,
    },
    isPublic: false,
  },
}
